---
title: "Figure Interior and Coastal mangroves compare"
---

```{r}
#| message: false
#| warning: false
library(ggplot2)
library(cowplot)
```

## Load figures

```{r}
alpha <- readRDS("rds/compare_mangroves/alpha_diversity_surface_plot.rds")

beta <- readRDS("rds/compare_mangroves/beta-diversity-surface-plot.rds")

core <- readRDS("rds/compare_mangroves/upset_surface_plot.rds")

dabar <- readRDS("rds/compare_mangroves/DA_barplot_surface.rds")

dahm <- readRDS("rds/compare_mangroves/DA_heatmap_surface.rds")
```

## Combine plots

```{r}
#| message: false
#| warning: false
beta_core <- plot_grid(beta, core, labels = c("B", "D)"),
                        label_fontface = "bold",
                        ncol = 1, rel_heights = c(0.8, 1))
beta_core_da <- plot_grid(beta_core, dahm, labels = c("", "C)"),
                        label_fontface = "bold",
                        ncol = 2, rel_widths = c(1, 0.9))
alpha_beta_core_da_2 <- plot_grid(alpha, beta_core_da,
                        ncol = 2, rel_widths = c(0.35, 1))
alpha_beta_core_da_2
```

```{r}
ggsave("Figures/SurfaceComparison/Fig2.SurfaceComparison_2.pdf",
       alpha_beta_core_da_2, width = 19, height = 12)
```
