---
title: "Differential Abundance"
---

# Load libraries and prepare data

```{r}
#| message: false
#| warning: false
# load libraries
library(phyloseq)
library(dplyr)
library(ANCOMBC)
library(tidyverse)
library(cowplot)
library(DT)
options(DT.options = list(
  initComplete = JS("function(settings, json) {",
                    "$(this.api().table().header()).css({'background-color':
  '#000', 'color': '#fff'});","}")))

```

```{r}
#load data
ps <- readRDS("rds/interior_impaired/physeq.rds")
```

# **Differential abundance ANCOMBC2** By Mangrove site

## **Prepare data**

```{r}
#| message: false
#| warning: false
# phyloseq to TreeSummarizedExperiment
tse <- mia::convertFromPhyloseq(ps)
#To manually change the reference level, not alphabdetic order
tse$Mangrove_system = factor(tse$Mangrove_system, levels = c("Impaired Términos Lagoon", "San Pedro River", "Fossil Lagoon"))


#variable
tse$Mangrove_system = factor(recode
                             (as.character(tse$Mangrove_system),
                             `Impaired Términos Lagoon` = "ITL",
                             `San Pedro River` = "SPR",
                             `Fossil Lagoon` = "FL",
                             .missing = "unknown"),
                             levels = c("ITL", "SPR", "FL"))
```

### 02.2 Run ANCOM-BC2

``` r
#| message: false
#| warning: false
output_location <- ancombc2(
  data = tse,
  assay_name = "counts",
  tax_level = "Order",
  fix_formula = "Mangrove_system + Depths",
  rand_formula = "(1 | ID)",
  p_adj_method = "holm",
  pseudo_sens = TRUE,
  prv_cut = 0.10,
  lib_cut = 1000,
  s0_perc = 0.05,
  group = "Mangrove_system",
  struc_zero = TRUE,
  neg_lb = TRUE,
  alpha = 0.05,
  n_cl = 2,
  verbose = TRUE,
  global = TRUE,
  pairwise = TRUE,
  dunnet = TRUE,
  trend = TRUE,
  iter_control = list(tol = 1e-2, max_iter = 20, verbose = TRUE),
  em_control = list(tol = 1e-5, max_iter = 100),
  lme_control = lme4::lmerControl(),
  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
  trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                              nrow = 2,
                                              byrow = TRUE),
                                       matrix(c(-1, 0, 1, -1),
                                              nrow = 2,
                                              byrow = TRUE),
                                       matrix(c(1, 0, 1, -1),
                                              nrow = 2,
                                              byrow = TRUE)),
                       node = list(2, 2, 1),
                       solver = "ECOS",
                       B = 100))

saveRDS(output_location, "rds/interior_impaired/output_location.rds")
```

```{r}
#| include: false
output_location <- readRDS("rds/interior_impaired/output_location.rds")
```

```{r}
#See results
res_pair_location <- output_location$res_pair

colnames(res_pair_location)
```

### 02.3 Get differential data

```{r}
# Create dataframe df_fig_pair1 to log-fold change (LFC) values
df_fig_pair1_location <- res_pair_location %>%
  dplyr::filter(`diff_Mangrove_systemSPR` == 1 |
                  `diff_Mangrove_systemFL` == 1 |
                  `diff_Mangrove_systemFL_Mangrove_systemSPR` == 1) %>%
  dplyr::mutate(lfc1 = ifelse(`diff_Mangrove_systemSPR` == 1, round(`lfc_Mangrove_systemSPR`, 2), NA),
                lfc2 = ifelse(`diff_Mangrove_systemFL` == 1, round(`lfc_Mangrove_systemFL`, 2), NA),
                lfc3 = ifelse(`diff_Mangrove_systemFL_Mangrove_systemSPR` == 1, round(`lfc_Mangrove_systemFL_Mangrove_systemSPR`, 2), NA)) %>%
  tidyr::pivot_longer(cols = lfc1:lfc3, names_to = "group", values_to = "value") %>%
  dplyr::arrange(taxon)
```

```{r}
# Create dataframe df_fig_pair2 to significant values
df_fig_pair2_location <- res_pair_location %>%
  dplyr::filter(`diff_Mangrove_systemSPR` == 1 |
                  `diff_Mangrove_systemFL` == 1 |
                  `diff_Mangrove_systemFL_Mangrove_systemSPR` == 1) %>%
  dplyr::mutate(lfc1 = ifelse(`passed_ss_Mangrove_systemSPR` == 1 & `diff_Mangrove_systemSPR` == 1, "darkblue", "black"),
                lfc2 = ifelse(`passed_ss_Mangrove_systemFL` == 1 & `diff_Mangrove_systemFL` == 1, "darkblue", "black"),
                lfc3 = ifelse(`passed_ss_Mangrove_systemFL_Mangrove_systemSPR` == 1 & `diff_Mangrove_systemFL_Mangrove_systemSPR` == 1, "darkblue", "black")) %>%
  tidyr::pivot_longer(cols = lfc1:lfc3, names_to = "group", values_to = "color") %>%
  dplyr::arrange(taxon)
```

```{r}
#| message: false
#| warning: false
# Combine dataframes df_fig_pair1 and df_fig_pair2
df_fig_pair_location <- df_fig_pair1_location %>%
  dplyr::left_join(df_fig_pair2_location, by = c("taxon", "group"))

# Rename groups
df_fig_pair_location$group <- recode(df_fig_pair_location$group,
                                     `lfc1` = "RSP vs ITL",
                                     `lfc2` = "FL vs ITL",
                                     `lfc3` = "FL vs RSP")

df_fig_pair_location$group <- factor(df_fig_pair_location$group,
                                     levels = c("RSP vs ITL",
                                                "FL vs ITL",
                                                "FL vs RSP"))


# Filter comparisons with significant values
df_fig_pair_location <- df_fig_pair_location %>%
  group_by(group) %>%
  filter(any(!is.na(value))) %>%
  ungroup()

# Calculate limits
lo <- floor(min(df_fig_pair_location$value, na.rm = TRUE))
up <- ceiling(max(df_fig_pair_location$value, na.rm = TRUE))
mid <- (lo + up) / 2
```

```{r}
head(df_fig_pair1_location)
head(df_fig_pair2_location)
```

::: callout-warning
## Important

The results indicated that there were no significant differences in the differential abundance of Phyla or Order between mangroves therefore it is not included in the final results.
:::
