project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

website:
  page-navigation: true
  title: "Microbial Diversity from a Fossil Lagoon and comparative Interior vs Coastal Mangroves"
  description: "Website of microbial diversity analysis of paper: tal tal tal"

  open-graph: true

  twitter-card:
    creator: "@HOaxacaDiana"

  page-footer:
    right: "This page is built with ❤ Science 🦠 🧬 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Diana Hernández-Oaxaca"
    center: "LandaLab"
    background: "#f1ebf9"

  sidebar:
    background: "#DEEBF7"
    logo: "images/landalab.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/DianaOaxaca/InteriorMangroves
        text: GitHub organization

    style: "docked"
    search: true
    collapse-level: 4

    contents:
      - text: Presentation
        href: 00.Presentation.qmd
      - text: Preprocessing
        href: 01.Preprocessing.qmd
      - section: "Interior and coastal mangroves compare"
        href: A_InteriorCoastalCompare.qmd
        contents:
          - section: "How similar are coastal and inland mangroves?"
            contents:
              - 02.SurfaceComparison.qmd
              - section: "Analysis"
                contents:
                  - 02.1.AlphaDiversity.qmd
                  - 02.2.BetaDiversity.qmd
                  - 02.3.Coremicrobiome.qmd
                  - 02.4.DifferentialAbundance.qmd
                  - 02.5.Fig2.InteriorCoastalCompare.qmd
      - section: "Interior mangroves explore"
        href: 03.InteriorMangroves.qmd
        contents:
          - section: "What makes inland mangroves different and unique?"
            contents:
              - 03.1.RelativeAbundances.qmd
              - 03.2.AlphaDiversity.qmd
              - 03.3.BetaDiversity.qmd
              - 03.4.Coremicrobiome.qmd
              - 03.5.DifferentialAbundance.qmd
              - 03.6.MetabolicInference.qmd
              - 03.7.Fig3.InteriorMangroves.qmd



format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    code-link: true
    anchor-sections: true
    footnotes-hover: false

freeze: auto

editor: visual

