{
  "hash": "f35c726ec289a9f0c082306c9658bde0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1) Community assembly processes (βNTI / RCbray)\"\n---\n\n# Community assembly processes\n\nWhich ecological processes — selection, dispersal, or drift — govern the assembly of inland relict sediment communities?❓\n\nWe use the phylogenetic null-model framework of Stegen et al., implemented in `iCAMP::qpen`, to partition pairwise community turnover into deterministic (selection) and stochastic (dispersal, drift) processes. **No ASVs were removed** prior to the analysis. βNTI is restricted to the inland relict sites, where a single primer-consistent dataset and a robust phylogenetic tree make the analysis well supported.\n\n## Load libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The analysis (βNTI / RCbray with iCAMP::qpen)\n\n### Import data and prepare matrices\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(iCAMP); library(phyloseq); library(qiime2R)\nset.seed(123)\nnperm  <- 999      # randomizations\nncores <- 4        # bajado por OOM (fork overcommit con muchos workers)\n\n# Import (same pipeline as the rest of the site)\nps <- qza_to_phyloseq(\n  features = \"data/ASV_table_filter_freq218_emc.qza\",\n  tree     = \"data/rooted-tree-iqtree.qza\",\n  taxonomy = \"data/taxonomy.qza\",\n  metadata = \"data/metadata2.tsv\"\n)\n\n# Rename systems as in 03.1.RelativeAbundances\nmetadata <- as(sample_data(ps), \"data.frame\") %>%\n  mutate(Location = case_when(\n    Location == \"El Cacahuate\"    ~ \"Fossil Lagoon\",\n    Location == \"La Piedad\"       ~ \"Reforma Waterfalls\",\n    Location == \"Dique Miguelito\" ~ \"Miguelito Dike\",\n    TRUE ~ Location))\nsample_data(ps) <- sample_data(metadata)\n\n# Community matrix (samples in rows) and phylogenetic distance — NO ASV filtering\ncomm <- as(otu_table(ps), \"matrix\")\nif (taxa_are_rows(ps)) comm <- t(comm)\ntree <- phy_tree(ps)\ncomunes <- intersect(colnames(comm), tree$tip.label)\ncomm <- comm[, comunes, drop = FALSE]\ntree <- ape::drop.tip(tree, setdiff(tree$tip.label, comunes))\npd <- cophenetic(tree)[colnames(comm), colnames(comm)]\n```\n:::\n\n\n### Run qpen per site and pooled\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeta_df <- data.frame(sample_data(ps))\ninteriores <- c(\"Fossil Lagoon\", \"Reforma Waterfalls\", \"Miguelito Dike\")\n\nrun_qpen <- function(samples, etiqueta) {\n  cm  <- comm[rownames(comm) %in% samples, , drop = FALSE]\n  cm  <- cm[, colSums(cm) > 0, drop = FALSE]\n  pdi <- pd[colnames(cm), colnames(cm)]\n  res <- qpen(comm = cm, pd = pdi, rand = nperm,\n              nworker = ncores, sig.bNTI = 2, sig.rc = 0.95)\n  res$result$grupo <- etiqueta\n  res$result\n}\n\nresultados <- lapply(interiores, function(s)\n  run_qpen(rownames(meta_df)[meta_df$Location == s], s))\nresultados[[\"pooled\"]] <- run_qpen(\n  rownames(meta_df)[meta_df$Location %in% interiores], \"All interiors (pooled)\")\n\ntodos <- bind_rows(resultados)\ndir.create(\"06.null-models-results\", showWarnings = FALSE)\nwrite_csv(todos, \"06.null-models-results/qpen_pairwise_all.csv\")\n\nresumen <- todos %>%\n  count(grupo, process) %>%\n  group_by(grupo) %>%\n  mutate(porcentaje = round(100 * n / sum(n), 1)) %>% ungroup()\nwrite_csv(resumen, \"06.null-models-results/qpen_process_summary.csv\")\n```\n:::\n\n\n### Significance of process differences between sites (Fisher's exact test)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# βNTI values are non-independent pairwise comparisons, so differences in\n# process composition between sites are tested with Fisher's exact test\n# (Benjamini-Hochberg correction), NOT linear mixed models.\nsitios <- c(\"Fossil Lagoon\", \"Reforma Waterfalls\", \"Miguelito Dike\")\ndat <- todos %>% filter(grupo %in% sitios)\n\ntabla <- dat %>%\n  count(grupo, process) %>%\n  pivot_wider(names_from = process, values_from = n, values_fill = 0) %>%\n  column_to_rownames(\"grupo\") %>% as.matrix()\n\npares <- combn(sitios, 2, simplify = FALSE)\nposthoc <- purrr::map_dfr(pares, function(pr) {\n  sub <- tabla[pr, ]; sub <- sub[, colSums(sub) > 0, drop = FALSE]\n  p <- fisher.test(sub, simulate.p.value = TRUE, B = 1e5)$p.value\n  tibble(sitio_1 = pr[1], sitio_2 = pr[2], p_raw = p)\n})\nposthoc$p_adj <- p.adjust(posthoc$p_raw, method = \"BH\")\nwrite_csv(posthoc, \"06.null-models-results/posthoc_process_differences.csv\")\n\nresumen_bnti <- dat %>%\n  group_by(grupo) %>%\n  summarise(n_pares = n(),\n            bNTI_medio = round(mean(bNTI), 2),\n            bNTI_sd    = round(sd(bNTI), 2),\n            pct_seleccion = round(100*mean(abs(bNTI) > 2), 1), .groups = \"drop\")\nwrite_csv(resumen_bnti, \"06.null-models-results/bNTI_summary_by_site.csv\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n\n```{.r .cell-code}\n###############################################################################\n#  SIGNIFICANCIA DE DIFERENCIAS EN PROCESOS DE ENSAMBLAJE ENTRE SITIOS\n#  Test de PERMUTACIÓN A NIVEL DE MUESTRA (no Fisher)\n#\n#  Por qué: los valores de βNTI son comparaciones PAREADAS no independientes\n#  (cada muestra participa en muchos pares). Fisher/chi2/LMM inflan la\n#  significancia por pseudoreplicación. La permutación a nivel de muestra\n#  respeta que la unidad independiente es la MUESTRA, no el par.\n#\n#  Lógica (estilo Stegen): se permutan las etiquetas de sitio sobre las\n#  muestras; en cada permutación se reconstruye qué pares quedan \"dentro\" de\n#  cada sitio y se recalcula el estadístico. La estructura pareada del βNTI\n#  NO se toca; solo se baraja la pertenencia de cada muestra a su sitio.\n###############################################################################\n\nlibrary(tidyverse)\nset.seed(123)\nnperm <- 9999   # permutaciones (9999 da p-values estables)\n\n## ---------------------------------------------------------------------------\n## 1. CARGAR los resultados pareados de qpen\n## ---------------------------------------------------------------------------\n# Necesitamos el archivo con TODOS los pares y su clasificación de proceso,\n# que incluya a qué muestra (sample1, sample2) corresponde cada par.\n# qpen$result trae columnas sample1, sample2, bNTI, RCbray, process.\npares <- read_csv(\"06.null-models-results/qpen_pairwise_all.csv\",\n                  show_col_types = FALSE)\n\n# Nos quedamos SOLO con pares interiores (los 3 sitios), no el pooled\n# (el pooled es un superset, no entra en la comparación entre sitios).\n# Si 'grupo' marca el subconjunto, filtramos los tres sitios:\nsitios <- c(\"Fossil Lagoon\", \"Reforma Waterfalls\", \"Miguelito Dike\")\n\n## ---------------------------------------------------------------------------\n## 2. MAPA muestra -> sitio\n## ---------------------------------------------------------------------------\n# Necesitamos saber a qué sitio pertenece cada muestra. Lo tomamos del metadata.\n# (ajustá la ruta/objeto si hace falta)\n# meta debe tener: SampleID, Location\nmeta <- read_tsv(\"data/metadata2.tsv\", show_col_types = FALSE)\n# renombrar como en el resto del proyecto\nmeta <- meta %>%\n  mutate(Location = case_when(\n    Location == \"El Cacahuate\"    ~ \"Fossil Lagoon\",\n    Location == \"La Piedad\"       ~ \"Reforma Waterfalls\",\n    Location == \"Dique Miguelito\" ~ \"Miguelito Dike\",\n    TRUE ~ Location)) %>%\n  filter(Location %in% sitios)\n\n# vector nombrado: nombre = SampleID, valor = sitio\ncol_id <- colnames(meta)[1]   # ajustá si el ID no es la 1a columna\nsample2site <- setNames(meta$Location, meta[[col_id]])\n\n## ---------------------------------------------------------------------------\n## 3. PARES INTRA-SITIO observados\n## ---------------------------------------------------------------------------\n# Para comparar la composición de procesos ENTRE sitios, usamos los pares\n# en los que AMBAS muestras pertenecen al mismo sitio (within-site pairs).\n# Detectar columnas de muestra en el data frame de pares:\n# qpen suele nombrarlas \"name1\"/\"name2\" o \"sample1\"/\"sample2\".\nnm <- names(pares)\nc1 <- nm[which(nm %in% c(\"sample1\",\"name1\",\"samp1\",\"s1\"))[1]]\nc2 <- nm[which(nm %in% c(\"sample2\",\"name2\",\"samp2\",\"s2\"))[1]]\nstopifnot(!is.na(c1), !is.na(c2))   # si falla, revisá los nombres reales\n\npares <- pares %>%\n  mutate(site1 = sample2site[.data[[c1]]],\n         site2 = sample2site[.data[[c2]]]) %>%\n  filter(!is.na(site1), !is.na(site2))\n\nintra <- pares %>% filter(site1 == site2) %>%\n  mutate(site = site1)\n\n## ---------------------------------------------------------------------------\n## 4. ESTADÍSTICO OBSERVADO\n## ---------------------------------------------------------------------------\n# Resumimos cada sitio por su % de proceso determinístico (selección) o,\n# más simple y robusto: el % de selección heterogénea (el proceso dominante).\n# Definimos un estadístico de diferencia entre dos sitios = diferencia\n# absoluta en la proporción de \"Heterogeneous.Selection\".\n\nprop_proceso <- function(df, proc = \"Heterogeneous.Selection\") {\n  df %>% group_by(site) %>%\n    summarise(p = mean(process == proc), .groups = \"drop\")\n}\n\nobs <- prop_proceso(intra)\n\nstat_pair <- function(tab, a, b) {\n  abs(tab$p[tab$site == a] - tab$p[tab$site == b])\n}\n\npares_sitios <- combn(sitios, 2, simplify = FALSE)\nobs_stats <- map_dbl(pares_sitios, ~ stat_pair(obs, .x[1], .x[2]))\nnames(obs_stats) <- map_chr(pares_sitios, ~ paste(.x, collapse = \" vs \"))\n\n## ---------------------------------------------------------------------------\n## 5. PERMUTACIÓN A NIVEL DE MUESTRA\n## ---------------------------------------------------------------------------\n# Barajamos la etiqueta de sitio sobre las MUESTRAS, reconstruimos los pares\n# intra-sitio bajo esa etiqueta permutada, y recalculamos el estadístico.\nmuestras   <- names(sample2site)\nsitios_obs <- unname(sample2site)\n\nperm_stats <- matrix(NA, nrow = nperm, ncol = length(obs_stats),\n                     dimnames = list(NULL, names(obs_stats)))\n\nfor (i in seq_len(nperm)) {\n  # barajar etiquetas de sitio entre muestras\n  perm_site <- setNames(sample(sitios_obs), muestras)\n  # reasignar sitio a cada muestra del par\n  s1 <- perm_site[ intra[[c1]] ]\n  s2 <- perm_site[ intra[[c2]] ]\n  keep <- s1 == s2                      # pares que quedan intra-sitio\n  tmp <- tibble(site = s1[keep], process = intra$process[keep])\n  tabp <- tmp %>% group_by(site) %>%\n    summarise(p = mean(process == \"Heterogeneous.Selection\"), .groups=\"drop\")\n  for (k in seq_along(pares_sitios)) {\n    a <- pares_sitios[[k]][1]; b <- pares_sitios[[k]][2]\n    pa <- tabp$p[tabp$site == a]; pb <- tabp$p[tabp$site == b]\n    perm_stats[i, k] <- if (length(pa) && length(pb)) abs(pa - pb) else NA\n  }\n}\n\n## ---------------------------------------------------------------------------\n## 6. P-VALORES (proporción de permutaciones >= observado) + BH\n## ---------------------------------------------------------------------------\np_raw <- map_dbl(seq_along(obs_stats), function(k) {\n  nulldist <- perm_stats[, k]; nulldist <- nulldist[!is.na(nulldist)]\n  (sum(nulldist >= obs_stats[k]) + 1) / (length(nulldist) + 1)  # +1 anti-cero\n})\np_adj <- p.adjust(p_raw, method = \"BH\")\n\nresultado <- tibble(\n  comparison = names(obs_stats),\n  obs_diff_hetSel = round(obs_stats, 3),\n  p_perm = round(p_raw, 4),\n  p_adj  = round(p_adj, 4)\n)\n\nprint(resultado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  comparison                           obs_diff_hetSel p_perm p_adj\n  <chr>                                          <dbl>  <dbl> <dbl>\n1 Fossil Lagoon vs Reforma Waterfalls            0.249  0.278 0.431\n2 Fossil Lagoon vs Miguelito Dike                0.2    0.287 0.431\n3 Reforma Waterfalls vs Miguelito Dike           0.049  0.810 0.810\n```\n\n\n:::\n\n```{.r .cell-code}\nwrite_csv(resultado, \"06.null-models-results/permutation_site_differences.csv\")\n\n## También guardamos las proporciones por sitio (para reportar descriptivo)\nproporciones <- intra %>%\n  count(site, process) %>%\n  group_by(site) %>%\n  mutate(pct = round(100 * n / sum(n), 1)) %>% ungroup()\nwrite_csv(proporciones, \"06.null-models-results/process_proportions_within_site.csv\")\n\nmessage(\"LISTO. permutation_site_differences.csv tiene los p-values honestos.\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLISTO. permutation_site_differences.csv tiene los p-values honestos.\n```\n\n\n:::\n\n```{.r .cell-code}\n###############################################################################\n```\n:::\n\n\n## Results and figures\n\n### Project colour palette\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Localities — consistent with the rest of the site (loc_colors)\nloc_colors <- c(\"Fossil Lagoon\"          = \"#A7fcc1\",\n                \"Reforma Waterfalls\"     = \"#44C17B\",\n                \"Miguelito Dike\"         = \"#2E8B57\",\n                \"All interiors (pooled)\" = \"#b2ffa1\")\n\n# Assembly processes — greens/teals coherent with the site\nprocess_colors <- c(\"Heterogeneous.Selection\" = \"#EFC7E6FF\",#ffeeff\n                    \"Homogeneous.Selection\"   = \"#A790DBFF\",#dcd3ff\n                    \"Dispersal.Limitation\"    = \"#D8D643FF\",#FFFFDD\n                    \"Homogenizing.Dispersal\"  = \"#1BB6AFFF\",#c4faf8\n                    \"Undominated\"             = \"gray80\") #gray70\n\nprocess_order <- c(\"Heterogeneous.Selection\",\"Homogeneous.Selection\",\n                   \"Dispersal.Limitation\",\"Homogenizing.Dispersal\",\"Undominated\")\ngroup_order   <- c(\"Fossil Lagoon\",\"Reforma Waterfalls\",\n                   \"Miguelito Dike\",\"All interiors (pooled)\")\n```\n:::\n\n\n### Load saved results\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntodos   <- read_csv(\"06.null-models-results/qpen_pairwise_all.csv\",\n                    show_col_types = FALSE)\nresumen <- read_csv(\"06.null-models-results/qpen_process_summary.csv\",\n                    show_col_types = FALSE)\n\ntodos$grupo     <- factor(todos$grupo, levels = group_order)\nresumen$grupo   <- factor(resumen$grupo, levels = group_order)\nresumen$process <- factor(resumen$process, levels = process_order)\n```\n:::\n\n\n### Fig 6A — βNTI distribution by group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbnti_plot <- ggplot(todos, aes(grupo, bNTI, fill = grupo)) +\n  geom_hline(yintercept = c(-2, 2), linetype = \"dashed\", colour = \"grey40\") +\n  geom_boxplot(width = 0.6, outlier.alpha = 0.3) +\n  geom_jitter(width = 0.15, alpha = 0.25, size = 0.6) +\n  scale_fill_manual(values = loc_colors) +\n  labs(x = NULL, y = expression(beta*\"NTI\")) +\n  theme_classic(base_size = 12) +\n  theme(legend.position = \"none\",\n        axis.text.x = element_text(angle = 0, hjust = 0.5))\n\nbnti_plot\n```\n\n::: {.cell-output-display}\n![](06.1.AssemblyProcesses_files/figure-html/fig-bnti-1.png){#fig-bnti width=720}\n:::\n:::\n\n\n> \\|βNTI\\| \\> 2 indicates selection; βNTI \\< −2 homogeneous selection, βNTI \\> 2 heterogeneous selection. The dashed lines mark the ±2 thresholds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(bnti_plot, \"rds/assembly_process/bntiplot.rds\")\n```\n:::\n\n\n### Fig 6B — Assembly process composition\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraupplot <- ggplot(resumen, aes(grupo, porcentaje, fill = process)) +\n  geom_col(width = 0.7) +\n  scale_fill_manual(values = process_colors, name = \"Assembly process\") +\n  labs(x = NULL, y = \"% of pairwise comparisons\") +\n  theme_classic(base_size = 12) +\n  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +\n  theme(legend.position = \"bottom\",\n        legend.title = element_text(size = 9),\n        legend.text = element_text(size = 8)) +\n  guides(fill = guide_legend(nrow = 2)) \n\nraupplot\n```\n\n::: {.cell-output-display}\n![](06.1.AssemblyProcesses_files/figure-html/fig-stacked-1.png){#fig-stacked width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(raupplot, \"rds/assembly_process/rcplot.rds\")\n```\n:::\n\n\n### Summary tables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposthoc <- read_csv(\"06.null-models-results/posthoc_process_differences.csv\",\n                    show_col_types = FALSE)\nbnti_site <- read_csv(\"06.null-models-results/bNTI_summary_by_site.csv\",\n                      show_col_types = FALSE)\n\nknitr::kable(bnti_site, caption = \"Mean βNTI per inland site.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Mean βNTI per inland site.\n\n|grupo              | n_pares| bNTI_medio| bNTI_sd| pct_seleccion|\n|:------------------|-------:|----------:|-------:|-------------:|\n|Fossil Lagoon      |      91|       0.85|    2.51|          39.6|\n|Miguelito Dike     |     276|       3.12|    4.62|          55.1|\n|Reforma Waterfalls |      66|       3.49|    3.49|          54.5|\n\n\n:::\n\n```{.r .cell-code}\nknitr::kable(posthoc,  caption = \"Fisher's exact test between sites (BH-adjusted).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Fisher's exact test between sites (BH-adjusted).\n\n|sitio_1            |sitio_2            |     p_raw|     p_adj|\n|:------------------|:------------------|---------:|---------:|\n|Fossil Lagoon      |Reforma Waterfalls | 0.0021400| 0.0064199|\n|Fossil Lagoon      |Miguelito Dike     | 0.0060899| 0.0091349|\n|Reforma Waterfalls |Miguelito Dike     | 0.1619684| 0.1619684|\n\n\n:::\n:::\n\n\n> **Key result.** Across all inland samples, deterministic selection dominated assembly (60.4% of comparisons; heterogeneous selection 50.4%), reproducibly across the three sites. Fossil Lagoon, the most isolated site, showed the largest contribution of dispersal limitation (mean βNTI 0.85), whereas the river sites were selection-dominated (mean βNTI 3.12 and 3.49). Fossil Lagoon differed from both river sites (Fisher, BH-adjusted *p* = 0.006 and 0.009), while the two river sites did not differ (*p* = 0.16).\n",
    "supporting": [
      "06.1.AssemblyProcesses_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}