{
  "hash": "9ccdceebc31587bbfe642e799d1404fa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Beta diversity\"\n---\n\n# Load libraries and prepare data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load libraries\nlibrary(vegan)\nlibrary(phyloseq)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tidyverse)\nlibrary(pairwiseAdonis)\nlibrary(reshape2)\nlibrary(ggpubr)\nlibrary(cowplot)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load data\nps <- readRDS(\"rds/interior_mangroves/phyloseq.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract data from phyloseq object\n#library(phyloseq)\notu_data <- otu_table(ps, taxa_are_rows = TRUE)\nmetadata <- as(sample_data(ps), \"data.frame\")\nsample_data <- data.frame(sample_data(ps))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# color pallet\ndepth_colors <- c(\"0-15\" = \"#f5e5c4\",\n                 \"16-30\" = \"#baa179\",\n                 \"31-45\" = \"#a67451\",\n                 \"50-75\" = \"#80673b\")\n\nloc_colors <- c(\"Fossil Lagoon\"= \"#A3D9A8\",\n                \"Reforma Waterfalls\" = \"#44C17B\",\n                \"Miguelito Dike\" = \"#2E8B57\")\n```\n:::\n\n\n# 01. Weighted Unifrac\n\n## 01.1 All samples\n\n### 01.1.1 Get distances and stress\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NMDS wu\nset.seed(123)\nnmds_wunifrac <- ordinate(ps, method = \"NMDS\", distance = \"wunifrac\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRun 0 stress 0.08872428 \nRun 1 stress 0.1347575 \nRun 2 stress 0.09235402 \nRun 3 stress 0.09235405 \nRun 4 stress 0.08872426 \n... New best solution\n... Procrustes: rmse 6.425539e-05  max resid 0.0003666809 \n... Similar to previous best\nRun 5 stress 0.09430901 \nRun 6 stress 0.09235403 \nRun 7 stress 0.1162806 \nRun 8 stress 0.09673622 \nRun 9 stress 0.09430906 \nRun 10 stress 0.1206369 \nRun 11 stress 0.09430906 \nRun 12 stress 0.09235406 \nRun 13 stress 0.1165466 \nRun 14 stress 0.09412556 \nRun 15 stress 0.09412561 \nRun 16 stress 0.08872432 \n... Procrustes: rmse 0.0001102589  max resid 0.0006660331 \n... Similar to previous best\nRun 17 stress 0.08872434 \n... Procrustes: rmse 6.312694e-05  max resid 0.0003921621 \n... Similar to previous best\nRun 18 stress 0.08872426 \n... Procrustes: rmse 6.783368e-05  max resid 0.0004037817 \n... Similar to previous best\nRun 19 stress 0.08872427 \n... Procrustes: rmse 3.662847e-05  max resid 0.0002002216 \n... Similar to previous best\nRun 20 stress 0.08872425 \n... New best solution\n... Procrustes: rmse 5.505287e-05  max resid 0.0003272047 \n... Similar to previous best\n*** Best solution repeated 1 times\n```\n\n\n:::\n\n```{.r .cell-code}\n# stress variable\nvar_stress_nmds_wu <- round(nmds_wunifrac$stress, 5)\nvar_stress_nmds_wu\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08872\n```\n\n\n:::\n:::\n\n\n### 01.1.2 Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert Depth to factor \nsample_data(ps)$Depths <- factor(sample_data(ps)$Depths, levels = c(\"0-15\", \"16-30\", \"31-45\", \"50-75\"))\n\n#plot\nnmds_wu <- plot_ordination(ps, nmds_wunifrac, color = \"Depths\") + theme_classic() + \n  labs(col = \"Depth\") + \n  labs(title=\"Weighted UniFrac\") +\n  geom_point(size=5) +\n    scale_fill_manual(values = depth_colors)+ \n    scale_color_manual(values = depth_colors)\n\nnmds_wu <- nmds_wu +\n  annotate(\"text\", x = Inf, y = -Inf, label = paste(\"Stress:\", var_stress_nmds_wu),\n           hjust = 1.1, vjust = -1.1, size = 4)\n\n#show\nnmds_wu\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### 01.1.3 PERMANOVA\n\n::: callout-note\nTo test the effects of Depth and Location on the Weighted Unifrac dissimilarity, a PERMANOVA analysis was conducted using adonis2.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# UniFrac\nwunifrac_distances <- UniFrac(ps, weighted = TRUE)\n\n# Convert distances 'dist' class\nwunifrac_distances <- as.dist(wunifrac_distances)\n\n# PERMANOVA \nset.seed(123)\nadonis2_wunifrac <- adonis2(\n  wunifrac_distances ~ Depths + Location,\n  data = metadata,\n  permutations = 999,\n  strata = metadata$ID,\n  by = \"terms\")\n\n# Results\nperm_results <- data.frame(\n  Term = c(\"Depth_cm\", \"Location\", \"Residual\"),\n  R2 = c(adonis2_wunifrac$R2[1], adonis2_wunifrac$R2[2], adonis2_wunifrac$R2[3]),\n  p_value = c(adonis2_wunifrac$`Pr(>F)`[1], adonis2_wunifrac$`Pr(>F)`[2], NA))\n\nperm_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Term        R2 p_value\n1 Depth_cm 0.2256078   0.001\n2 Location 0.1821115   0.002\n3 Residual 0.5922807      NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# PERMANOVA text\nperm_text <- paste(\n  \"PERMANOVA:\",\n  paste(\"Depths: R² =\", round(perm_results$R2[1], 3), \", p =\", perm_results$p_value[1]),\n  paste(\"Location: R² =\", round(perm_results$R2[2], 3), \", p =\", perm_results$p_value[2]),\n  paste(\"Residual: R² =\", round(perm_results$R2[3], 3)),\n  sep = \"\\n\")\n```\n:::\n\n\n### 01.1.4 Plot with permanova\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add to plot\nnmds_wu <- nmds_wu +\n  annotate(\n    \"text\", x = Inf, y = Inf, label = perm_text,\n    hjust = 1.1, vjust = 1.6, size = 3, color = \"black\"\n  )\n\n# Mostrar el gráfico\nnmds_wu\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/nmds_wunifrac_all.pdf\", nmds_wu, width = 20, height = 15, units = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: No shared levels found between `names(values)` of the manual scale and the\ndata's fill values.\n```\n\n\n:::\n:::\n\n\n## 01.2 Surface and deep samples\n\n### 01.2.1 Filter depths\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter data 0-15 y 50-75\nsample_data(ps)$Depths_fltr <- factor(sample_data(ps)$Depths, levels = c(\"0-15\", \"50-75\"))\n\nps_fltr <- prune_samples(sample_data(ps)$Depths_fltr %in% c(\"0-15\", \"50-75\"), ps)\n\nmetadata_fltr <- as(sample_data(ps_fltr), \"data.frame\")\n```\n:::\n\n\n### 01.2.2 Get distances and stress\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distances\nset.seed(123)\nnmds_wunifrac_fltr <- ordinate(ps_fltr, method = \"NMDS\", distance = \"wunifrac\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRun 0 stress 0.06140161 \nRun 1 stress 0.06140161 \n... Procrustes: rmse 1.375984e-05  max resid 4.526863e-05 \n... Similar to previous best\nRun 2 stress 0.06140161 \n... Procrustes: rmse 1.040159e-05  max resid 4.144454e-05 \n... Similar to previous best\nRun 3 stress 0.07281446 \nRun 4 stress 0.07281446 \nRun 5 stress 0.07281446 \nRun 6 stress 0.06140162 \n... Procrustes: rmse 1.995929e-05  max resid 7.559328e-05 \n... Similar to previous best\nRun 7 stress 0.08794268 \nRun 8 stress 0.07281447 \nRun 9 stress 0.08794276 \nRun 10 stress 0.07281446 \nRun 11 stress 0.1000555 \nRun 12 stress 0.06140161 \n... New best solution\n... Procrustes: rmse 2.65057e-06  max resid 7.365192e-06 \n... Similar to previous best\nRun 13 stress 0.06140163 \n... Procrustes: rmse 2.634859e-05  max resid 9.25293e-05 \n... Similar to previous best\nRun 14 stress 0.07281446 \nRun 15 stress 0.06140164 \n... Procrustes: rmse 4.98994e-05  max resid 0.0001535384 \n... Similar to previous best\nRun 16 stress 0.06140162 \n... Procrustes: rmse 2.22653e-05  max resid 8.271611e-05 \n... Similar to previous best\nRun 17 stress 0.07281446 \nRun 18 stress 0.08794313 \nRun 19 stress 0.1000555 \nRun 20 stress 0.1047482 \n*** Best solution repeated 4 times\n```\n\n\n:::\n\n```{.r .cell-code}\n# stress\nvar_stress_nmds_wu_fltr <- round(nmds_wunifrac_fltr$stress, 5)\n```\n:::\n\n\n### 01.2.3 NMDS plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot NMDS\nnmds_wu_fltr <- plot_ordination(ps_fltr, nmds_wunifrac_fltr, color = \"Depths\") + \n  theme_classic() + \n  labs(col = \"Depths\") + \n  labs(title = \"Weighted UniFrac\") +\n  geom_point(size = 5) +\n  scale_fill_manual(values = depth_colors) + \n  scale_color_manual(values = depth_colors)\n\n# add stress\nnmds_wu_fltr <- nmds_wu_fltr +\n  annotate(\"text\", x = Inf, y = -Inf, label = paste(\"Stress:\", var_stress_nmds_wu_fltr),\n           hjust = 1.1, vjust = -1.2, size = 3)\n```\n:::\n\n\n### 01.2.4 PERMANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# UniFrac distances\nwunifrac_distances_fltr <- UniFrac(ps_fltr, weighted = TRUE)\n\n# Convert 'dist' class\nwunifrac_distances_fltr <- as.dist(wunifrac_distances_fltr)\n\n# PERMANOVA \nset.seed(123)\nadonis2_wunifrac_fltr <- adonis2(\n  wunifrac_distances_fltr ~ Depths_fltr + Location,\n  data = metadata_fltr,\n  permutations = 999,\n  strata = metadata_fltr$ID,\n  by = \"terms\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSet of permutations < 'minperm'. Generating entire set.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Results\nperm_results_fltr <- data.frame(\n  Term = c(\"Depth_cm\", \"Location\", \"Residual\"),\n  R2 = c(adonis2_wunifrac_fltr$R2[1], adonis2_wunifrac_fltr$R2[2], adonis2_wunifrac_fltr$R2[3]),\n  p_value = c(adonis2_wunifrac_fltr$`Pr(>F)`[1], adonis2_wunifrac_fltr$`Pr(>F)`[2], NA))\n\nperm_results_fltr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Term         R2 p_value\n1 Depth_cm 0.34646671   0.002\n2 Location 0.09315353   0.157\n3 Residual 0.56037976      NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# PERMANOVA text\nperm_text_fltr <- paste(\n  \"PERMANOVA:\",\n  paste(\"Depths: R² =\", round(perm_results_fltr$R2[1], 3), \", p =\", perm_results_fltr$p_value[1]),\n  paste(\"Location: R² =\", round(perm_results_fltr$R2[2], 3), \", p =\", perm_results_fltr$p_value[2]), sep = \"\\n\")\n```\n:::\n\n\n### 01.2.5 Post-hoc adonis\n\n::: callout-note\nTo test differences between the Mangrove systems a Post-hoc pairwise PERMANOVA was conducted using pairwise.adonis\n:::\n\n### 01.2.6 Pairwise adonis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Post-hoc Depths\n# Pairwise PERMANOVA  Weighted UniFrac\nset.seed(123)\npairwise_adonis_fltr <- pairwiseAdonis::pairwise.adonis2(\n  wunifrac_distances_fltr ~ Depths_fltr,\n  data = metadata_fltr,\n  permutations = 999)\n\n# show\npairwise_adonis_fltr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$parent_call\n[1] \"wunifrac_distances_fltr ~ Depths_fltr , strata = Null , permutations 999\"\n\n$`0-15_vs_50-75`\n         Df SumOfSqs      R2      F Pr(>F)    \nModel     1  0.23722 0.34647 11.663  0.001 ***\nResidual 22  0.44745 0.65353                  \nTotal    23  0.68467 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nattr(,\"class\")\n[1] \"pwadstrata\" \"list\"      \n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract pairwise adonis results\npairwise_text_fltr <- paste(\n  \"Pairwise PERMANOVA Depths:\",\n  paste(\"R² =\", round(pairwise_adonis_fltr$`0-15_vs_50-75`$R2[1], 3), \n        \", p =\", pairwise_adonis_fltr$`0-15_vs_50-75`$`Pr(>F)`[1]),\n  sep = \"\\n\")\n```\n:::\n\n\n### 01.2.7 Beta disper\n\n::: callout-important\nGiven the pairwise PERMANOVA showed a highly significant result (p = 0.001), it is prudent to calculate the beta dispersion to validate that this result reflects real differences in microbial community composition between “0-15” and “50-75,” and not just differences in variability within each depth. In addition, R² = 0.346 indicates a moderate effect, but the 65.4% residual variance suggests unexplained variability, which could include differences in dispersion.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Beta disp\nbeta_disp_fltr <- betadisper(wunifrac_distances_fltr, metadata_fltr$Depths_fltr)\n\n# Significant test\nanova_beta_disp_fltr <- anova(beta_disp_fltr)\nanova_beta_disp_fltr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Distances\n          Df   Sum Sq   Mean Sq F value Pr(>F)\nGroups     1 0.001293 0.0012934  0.3525 0.5587\nResiduals 22 0.080716 0.0036689               \n```\n\n\n:::\n\n```{.r .cell-code}\n# betadisp wu by loc\nbeta_disp_fltr_loc <- betadisper(wunifrac_distances_fltr, metadata_fltr$Location)\nanova_beta_disp_fltr <- anova(beta_disp_fltr_loc)\nanova_beta_disp_fltr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Distances\n          Df   Sum Sq   Mean Sq F value Pr(>F)\nGroups     2 0.008101 0.0040507  0.7994 0.4628\nResiduals 21 0.106414 0.0050673               \n```\n\n\n:::\n\n```{.r .cell-code}\n# Show dispersion by group\nbeta_disp_fltr$group.distances\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     0-15     50-75 \n0.1321581 0.1174246 \n```\n\n\n:::\n\n```{.r .cell-code}\n# boxplot betadisper\nbeta_data_fltr <- data.frame(\n  Group = metadata_fltr$Depths_fltr,\n  Distance_to_centroid = beta_disp_fltr$distances\n)\nbeta_plot_fltr <- ggplot(beta_data_fltr, aes(x = Group, y = Distance_to_centroid, fill = Group)) +\n  geom_boxplot() +\n  scale_fill_manual(values = depth_colors) +\n  labs(title = \"Betadisper by depth wUniFrac\") +\n  theme_classic()\n\n#show\nbeta_plot_fltr\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nSave boxplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/Betadisper_depth.pdf\", beta_plot_fltr, bg='transparent', width = 4, height = 4.5)\n```\n:::\n\n\n### 01.2.8 Plot with PERMANOVA, pairwise PERMANOVA and Betadisper\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add betadisper p-value text\nbeta_text_fltr <- paste(\"Betadisper p-value:\", round(anova_beta_disp_fltr$`Pr(>F)`[1], 3))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Añadir texto de PERMANOVA y dispersión beta\nnmds_wu_fltr <- nmds_wu_fltr +\n  annotate(\n    \"text\", x = Inf, y = Inf, \n    label = paste(perm_text_fltr, pairwise_text_fltr, beta_text_fltr, sep = \"\\n\"),\n    hjust = 1.1, vjust = 1.2, size = 3, color = \"black\")\nnmds_wu_fltr\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nsave\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/NMDS_wu_depth.pdf\", nmds_wu_fltr, bg='transparent', width = 6, height = 4.5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: No shared levels found between `names(values)` of the manual scale and the\ndata's fill values.\n```\n\n\n:::\n:::\n\n\n# 02. Unweighted UniFrac\n\n## 02.1 Get distances and stress\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Unweighted UniFrac\nnmds_unifrac <- ordinate(ps, method = \"NMDS\", distance = \"unifrac\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRun 0 stress 0.07828522 \nRun 1 stress 0.07828508 \n... New best solution\n... Procrustes: rmse 6.388879e-05  max resid 0.0004102816 \n... Similar to previous best\nRun 2 stress 0.08566906 \nRun 3 stress 0.09757136 \nRun 4 stress 0.09289173 \nRun 5 stress 0.09405995 \nRun 6 stress 0.09641279 \nRun 7 stress 0.09988806 \nRun 8 stress 0.4025261 \nRun 9 stress 0.1117382 \nRun 10 stress 0.09405983 \nRun 11 stress 0.09989714 \nRun 12 stress 0.07828528 \n... Procrustes: rmse 0.0004409903  max resid 0.002838493 \n... Similar to previous best\nRun 13 stress 0.09642043 \nRun 14 stress 0.09288072 \nRun 15 stress 0.09754486 \nRun 16 stress 0.07828522 \n... Procrustes: rmse 6.12037e-05  max resid 0.0003916262 \n... Similar to previous best\nRun 17 stress 0.1040502 \nRun 18 stress 0.07828555 \n... Procrustes: rmse 0.0005301794  max resid 0.00341265 \n... Similar to previous best\nRun 19 stress 0.08566868 \nRun 20 stress 0.1000177 \n*** Best solution repeated 4 times\n```\n\n\n:::\n\n```{.r .cell-code}\n# stress variable\nvar_stress_nmds_u <- round(nmds_unifrac$stress, 5)\nvar_stress_nmds_u\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07829\n```\n\n\n:::\n:::\n\n\n## 02.2 NMDS\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reorder 'Location'\nsample_data(ps)$Location <- factor(sample_data(ps)$Location, levels = c(\"Fossil Lagoon\", \"Reforma Waterfalls\", \"Miguelito Dike\"))\n\n# NMDS\nnmds_u <- plot_ordination(ps, nmds_unifrac, color = \"Location\") + \n  theme_classic() + \n  labs(col = \"Location\", title = \"Unweighted UniFrac\") +\n  geom_point(size = 5) +\n  scale_fill_manual(values = loc_colors) + \n  scale_color_manual(values = loc_colors) +\n  annotate(\"text\", x = Inf, y = -Inf, \n           label = paste(\"Stress:\", var_stress_nmds_u),\n           hjust = 1.1, vjust = -1.3, size = 3)\n```\n:::\n\n\n## 02.3 PERMANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# UniFrac distances\nunifrac_distances <- UniFrac(ps, weighted = FALSE)\n\n# Convert 'dist' class\nunifrac_distances <- as.dist(unifrac_distances)\n\n# PERMANOVA \nset.seed(123)\nadonis2_unifrac <- adonis2(\n  unifrac_distances ~ Location + Depths,\n  data = metadata,\n  permutations = 999,\n  strata = metadata$ID,\n  by = \"terms\")\n\n# Results\nperm_results <- data.frame(\n  Term = c(\"Location\",\"Depths\", \"Residual\"),\n  R2 = c(adonis2_unifrac$R2[1], adonis2_unifrac$R2[2], adonis2_unifrac$R2[3]),\n  p_value = c(adonis2_unifrac$`Pr(>F)`[1], adonis2_unifrac$`Pr(>F)`[2], NA))\n\nperm_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Term        R2 p_value\n1 Location 0.3010881   0.001\n2   Depths 0.1355837   0.001\n3 Residual 0.5633282      NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# PERMANOVA text\nperm_text <- paste(\n  \"PERMANOVA:\",\n  paste(\"Location: R² =\", round(perm_results$R2[1], 3), \", p =\", perm_results$p_value[1]),\n  paste(\"Depths: R² =\", round(perm_results$R2[2], 3), \", p =\", perm_results$p_value[2]), sep = \"\\n\")\n```\n:::\n\n\n## 02.4 Post-hoc adonis\n\n::: callout-important\nTo test differences between the Mangrove systems a Post-hoc pairwise PERMANOVA was conducted using pairwise.adonis\n:::\n\n## 02.5 Pairwise adonis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Post-hoc Location\n# Pairwise PERMANOVA  Weighted UniFrac\nset.seed(123)\npairwise_adonis_u <- pairwiseAdonis::pairwise.adonis2(\n  unifrac_distances ~ Location + Depths,\n  data = metadata,\n  permutations = 999)\n\n# show\npairwise_adonis_u\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$parent_call\n[1] \"unifrac_distances ~ Location + Depths , strata = Null , permutations 999\"\n\n$`Miguelito Dike_vs_Reforma Waterfalls`\n         Df SumOfSqs     R2      F Pr(>F)   \nModel     4   0.9309 0.2883 3.1394  0.002 **\nResidual 31   2.2980 0.7117                 \nTotal    35   3.2289 1.0000                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$`Miguelito Dike_vs_Fossil Lagoon`\n         Df SumOfSqs      R2     F Pr(>F)    \nModel     4   1.5976 0.41067 5.749  0.001 ***\nResidual 33   2.2926 0.58933                 \nTotal    37   3.8902 1.00000                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n$`Reforma Waterfalls_vs_Fossil Lagoon`\n         Df SumOfSqs      R2      F Pr(>F)    \nModel     4  1.14825 0.59947 7.8578  0.001 ***\nResidual 21  0.76718 0.40053                  \nTotal    25  1.91543 1.00000                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nattr(,\"class\")\n[1] \"pwadstrata\" \"list\"      \n```\n\n\n:::\n:::\n\n\n## 02.6 Extract p-values\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define abbrevs\nlocation_abbrevs <- c(\n  \"Miguelito Dike\" = \"MD\",\n  \"Reforma Waterfalls\" = \"RW\",\n  \"Fossil Lagoon\" = \"FL\")\n\n# Extract values\nlocations <- unique(metadata$Location)\np_matrix <- matrix(NA, nrow = length(locations), ncol = length(locations),\n                   dimnames = list(locations, locations))\nr2_matrix <- matrix(NA, nrow = length(locations), ncol = length(locations),\n                    dimnames = list(locations, locations))\n\nfor (comp in names(pairwise_adonis_u)[-1]) {  # Exclude 'parent_call'\n  pair <- strsplit(comp, \"_vs_\")[[1]]\n  loc1 <- pair[1]\n  loc2 <- pair[2]\n  p_matrix[loc1, loc2] <- pairwise_adonis_u[[comp]]$`Pr(>F)`[1]\n  p_matrix[loc2, loc1] <- pairwise_adonis_u[[comp]]$`Pr(>F)`[1]  # Simetric\n  r2_matrix[loc1, loc2] <- pairwise_adonis_u[[comp]]$R2[1]\n  r2_matrix[loc2, loc1] <- pairwise_adonis_u[[comp]]$R2[1]  # Sim\n}\ndiag(p_matrix) <- 1  # p-value = 1 \ndiag(r2_matrix) <- 0  # R² = 0 \n\n# abbrevs in matrix\nabbrev_locations <- location_abbrevs[locations]\nnames(abbrev_locations) <- NULL\ndimnames(p_matrix) <- list(abbrev_locations, abbrev_locations)\ndimnames(r2_matrix) <- list(abbrev_locations, abbrev_locations)\n\n# Convert to long format\np_melt <- melt(p_matrix, na.rm = TRUE)\ncolnames(p_melt) <- c(\"Location1\", \"Location2\", \"p_value\")\nr2_melt <- melt(r2_matrix, na.rm = TRUE)\ncolnames(r2_melt) <- c(\"Location1\", \"Location2\", \"R2\")\n```\n:::\n\n\n## 02.7 Heatmap\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Heatmap of p-values\nheatmap_plot_p <- ggplot(p_melt, aes(x = Location1, y = Location2, fill = p_value)) +\n  geom_tile(color = \"gray40\") +\n  scale_fill_gradient2(low = \"white\", mid = \"white\", high = \"gray40\",\n                       midpoint = 0.025, limits = c(0, 1),\n                       name = \"p-value\") +\n  geom_text(aes(label = sprintf(\"%.3f\", p_value)), color = \"black\", size = 3) +\n  theme_minimal() +\n  labs(title = \"Pairwise PERMANOVA Unweighted UniFrac\", y = \"Location\") +\n  theme(axis.text.x = element_blank(),  # Ocult axis x\n        axis.title.x = element_blank(),\n        axis.title.y = element_text(size = 12),\n        plot.title = element_text(size = 12))\n\n# Heatmap de R²\nheatmap_plot_r2 <- ggplot(r2_melt, aes(x = Location1, y = Location2, fill = R2)) +\n  geom_tile(color = \"gray40\") +\n  scale_fill_gradient(low = \"white\", high = \"gray40\",\n                      name = \"R²\") +\n  geom_text(aes(label = sprintf(\"%.3f\", R2)), color = \"black\", size = 3) +\n  theme_minimal() +\n  labs(title = NULL,\n       x = \"Location\", y = \"Location\") +\n  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 9),\n        axis.title = element_text(size = 12),\n        plot.title = element_text(size = 10))\n\n# join cowplot\ncombined_heatmap <- plot_grid(\n  heatmap_plot_p, heatmap_plot_r2,\n  nrow = 2, align = \"v\", axis = \"lr\")\n\n# show\ncombined_heatmap\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nsave\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/pairwiseheatmap.pdf\", combined_heatmap, bg='transparent', width = 4, height = 4.5)\n```\n:::\n\n\n## 02.8 Beta disper\n\n::: callout-important\nGiven the pairwise PERMANOVA showed a highly significant results, it is prudent to calculate the beta dispersion to validate that this result reflects real differences in microbial community composition between mangrove location and not just differences in variability within mangrove site.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Beta disp\nbeta_disp_u <- betadisper(unifrac_distances, metadata$Location)\nanova_beta_disp_u <- anova(beta_disp_u)\n\n#bet disp depth\nbeta_disp_u_d <- betadisper(unifrac_distances, metadata$Depths)\nanova_beta_disp_u_d <- anova(beta_disp_u_d)\n\n# Show dispersion by group\nbeta_disp_u$group.distances\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Fossil Lagoon     Miguelito Dike Reforma Waterfalls \n         0.2159625          0.2698631          0.2308628 \n```\n\n\n:::\n\n```{.r .cell-code}\n# boxplot betadisper\nbeta_data <- data.frame(\n  Group = metadata$Location,\n  Distance_to_centroid = beta_disp_u$distances\n)\nbeta_plot <- ggplot(beta_data, aes(x = Group, y = Distance_to_centroid, fill = Group)) +\n  geom_boxplot() +\n  scale_fill_manual(values = loc_colors) +\n  labs(title = \"Betadisper by location wUniFrac\") +\n  theme_classic()\n\n#show\nbeta_plot\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/Betadisper_location.pdf\", beta_plot, bg='transparent', width = 5.5, height = 4)\n```\n:::\n\n\n## 02.9 Plot with PERMANOVA, pairwise PERMANOVA and Betadisper\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeta_text <- paste(\"Betadisper, p-value:\", \n                   round(anova_beta_disp_u$`Pr(>F)`[1], 3))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add texts to NMDS\nnmds_u <- nmds_u +\n  annotate(\n    \"text\", x = Inf, y = Inf, \n    label = paste(perm_text, beta_text, sep = \"\\n\"),\n    hjust = 1.1, vjust = 1.2, size = 3, color = \"black\"\n  )\n```\n:::\n\n\nSave\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/NMDS_u_location.pdf\", nmds_u, bg='transparent', width = 6, height = 4.5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: No shared levels found between `names(values)` of the manual scale and the\ndata's fill values.\n```\n\n\n:::\n:::\n\n\n# 03. dbRDA\n\n## 03.1 Load an prepare data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read data\nphychem <- read.csv(\"data/physicochemists.csv\", stringsAsFactors = FALSE)\n\n# Rename specific levels\nphychem <- phychem %>%\n  mutate(`Locality` = case_when(\n    Locality == \"El Cacahuate\" ~ \"Fossil Lagoon\",\n    Locality == \"La Piedad\" ~ \"Reforma Waterfalls\",\n    Locality == \"Dique Miguelito\" ~ \"Miguelito Dike\",\n    TRUE ~ Locality))\n\n# extract intersticial samples 30 cm\nps_phychem30cm <- prune_samples(sample_data(ps)$Depths == \"31-45\", ps)\n\n# Extract metadata from filter object\nmetadata_phychem30cm <- as.data.frame(sample_data(ps_phychem30cm))\n\n# convert to data frame\nmetadata_phychem30cm_df <- data.frame(as(sample_data(ps_phychem30cm), \n                                         \"data.frame\"))\n# join\ncombined_metadata <- merge(metadata_phychem30cm_df, phychem,\n                           by = \"Sample\", all.x = TRUE)\n\n# rownames\nrownames(combined_metadata) <- combined_metadata$Sample\n\n# Convert to sample_data\nsample_data_combined <- sample_data(combined_metadata)\n\n# save into phyloseq object\nsample_data(ps_phychem30cm) <- sample_data_combined\n```\n:::\n\n\n## 03.2 Get distances\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcular las distancias Unifrac no ponderadas\nunifrac_distances_phychem30cm<- distance(ps_phychem30cm, method = \"unifrac\", weighted = FALSE)\n```\n:::\n\n\n## 03.3 Calculate dbRDA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert distance matrix to vegdist object\nunifrac_vegdist_phychem30cm <- as.dist(unifrac_distances_phychem30cm)\n\n# db-RDA\ndbrda_result <- capscale(unifrac_vegdist_phychem30cm ~ Temperature...C. + \n                           Salinity..ppm. + pH + Redox.mV..Eh. + \n                           S.2..mg.l. + SO....mg.l., data = phychem)\n\n# summary\nsummary(dbrda_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ncapscale(formula = unifrac_vegdist_phychem30cm ~ Temperature...C. +      Salinity..ppm. + pH + Redox.mV..Eh. + S.2..mg.l. + SO....mg.l.,      data = phychem) \n\nPartitioning of squared Unknown distance:\n              Inertia Proportion\nTotal          0.9946     1.0000\nConstrained    0.6091     0.6124\nUnconstrained  0.3855     0.3876\n\nEigenvalues, and their contribution to the squared Unknown distance \n\nImportance of components:\n                        CAP1   CAP2    CAP3    CAP4    CAP5    CAP6   MDS1\nEigenvalue            0.3237 0.1167 0.08140 0.04026 0.02632 0.02068 0.2614\nProportion Explained  0.3255 0.1173 0.08185 0.04048 0.02646 0.02079 0.2628\nCumulative Proportion 0.3255 0.4428 0.52469 0.56516 0.59163 0.61242 0.8753\n                         MDS2    MDS3    MDS4    MDS5    MDS6\nEigenvalue            0.04246 0.02607 0.02423 0.01797 0.01334\nProportion Explained  0.04269 0.02621 0.02436 0.01807 0.01341\nCumulative Proportion 0.91795 0.94416 0.96852 0.98659 1.00000\n\nAccumulated constrained eigenvalues\nImportance of components:\n                        CAP1   CAP2   CAP3    CAP4    CAP5    CAP6\nEigenvalue            0.3237 0.1167 0.0814 0.04026 0.02632 0.02068\nProportion Explained  0.5315 0.1916 0.1336 0.06609 0.04321 0.03395\nCumulative Proportion 0.5315 0.7231 0.8567 0.92284 0.96605 1.00000\n```\n\n\n:::\n:::\n\n\n## 03.4 Get significance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Significance\nanova_axes <- anova(dbrda_result, by = \"axis\", \n                    permutations = 999)\nanova_axes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nForward tests for axes\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = unifrac_vegdist_phychem30cm ~ Temperature...C. + Salinity..ppm. + pH + Redox.mV..Eh. + S.2..mg.l. + SO....mg.l., data = phychem)\n         Df SumOfSqs      F Pr(>F)\nCAP1      1  0.32374 5.0389  0.140\nCAP2      1  0.11671 2.1193  0.637\nCAP3      1  0.08140 1.6893  0.687\nCAP4      1  0.04026 0.9399  0.827\nCAP5      1  0.02632 0.6827  0.827\nCAP6      1  0.02068 0.5901  0.827\nResidual  6  0.38549              \n```\n\n\n:::\n\n```{.r .cell-code}\n# Significance by variable\nanova_terms <- anova(dbrda_result, by = \"terms\", \n                     permutations = 999)\n\nanova_terms\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = unifrac_vegdist_phychem30cm ~ Temperature...C. + Salinity..ppm. + pH + Redox.mV..Eh. + S.2..mg.l. + SO....mg.l., data = phychem)\n                 Df SumOfSqs      F Pr(>F)  \nTemperature...C.  1  0.20776 3.2337  0.016 *\nSalinity..ppm.    1  0.12036 1.8733  0.112  \npH                1  0.06417 0.9987  0.433  \nRedox.mV..Eh.     1  0.05053 0.7864  0.565  \nS.2..mg.l.        1  0.10751 1.6733  0.151  \nSO....mg.l.       1  0.05879 0.9151  0.470  \nResidual          6  0.38549                \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# variance by each axis\nsummary(dbrda_result)$cont$importance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                        CAP1   CAP2    CAP3    CAP4    CAP5    CAP6   MDS1\nEigenvalue            0.3237 0.1167 0.08140 0.04026 0.02632 0.02068 0.2614\nProportion Explained  0.3255 0.1173 0.08185 0.04048 0.02646 0.02079 0.2628\nCumulative Proportion 0.3255 0.4428 0.52469 0.56516 0.59163 0.61242 0.8753\n                         MDS2    MDS3    MDS4    MDS5    MDS6\nEigenvalue            0.04246 0.02607 0.02423 0.01797 0.01334\nProportion Explained  0.04269 0.02621 0.02436 0.01807 0.01341\nCumulative Proportion 0.91795 0.94416 0.96852 0.98659 1.00000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(dbrda_result, permutations = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = unifrac_vegdist_phychem30cm ~ Temperature...C. + Salinity..ppm. + pH + Redox.mV..Eh. + S.2..mg.l. + SO....mg.l., data = phychem)\n         Df SumOfSqs      F Pr(>F)  \nModel     6  0.60912 1.5801  0.095 .\nResidual  6  0.38549                \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## 03.5 PERMANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# PERMANOVA\nset.seed(123)\npermanova_result <- adonis2(unifrac_distances_phychem30cm ~ Temperature...C. + Salinity..ppm. + pH +\nRedox.mV..Eh. + S.2..mg.l. + SO....mg.l., \ndata = phychem, by=\"terms\", permutations = 999)\n\n# show\npermanova_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = unifrac_distances_phychem30cm ~ Temperature...C. + Salinity..ppm. + pH + Redox.mV..Eh. + S.2..mg.l. + SO....mg.l., data = phychem, permutations = 999, by = \"terms\")\n                 Df SumOfSqs      R2      F Pr(>F)  \nTemperature...C.  1  0.20776 0.20889 3.2337  0.017 *\nSalinity..ppm.    1  0.12036 0.12101 1.8733  0.122  \npH                1  0.06417 0.06451 0.9987  0.406  \nRedox.mV..Eh.     1  0.05053 0.05080 0.7864  0.565  \nS.2..mg.l.        1  0.10751 0.10809 1.6733  0.172  \nSO....mg.l.       1  0.05879 0.05911 0.9151  0.459  \nResidual          6  0.38549 0.38758                \nTotal            12  0.99461 1.00000                \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## 03.6 PERMANOVA Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract PERMANOVA results\npermanova_df <- data.frame(\n  Variable = rownames(permanova_result)[1:(nrow(permanova_result)-2)],\n  R2 = permanova_result$R2[1:(nrow(permanova_result)-2)],\n  p_value = permanova_result$`Pr(>F)`[1:(nrow(permanova_result)-2)])\n\n# names\nvar_abbrevs <- c(\n  \"Temperature...C.\" = \"Temperature\",\n  \"Salinity..ppm.\" = \"Salinity\",\n  \"pH\" = \"pH\",\n  \"Redox.mV..Eh.\" = \"Redox\",\n  \"S.2..mg.l.\" = \"S2\",\n  \"SO....mg.l.\" = \"Sulfates\")\n\npermanova_df$Variable <- var_abbrevs[permanova_df$Variable]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot\npermanova_plot <- ggplot(permanova_df, aes(x = Variable, \n                        y = R2, fill = p_value < 0.05)) +\n  geom_bar(stat = \"identity\") +\n  scale_fill_manual(values = c(\"TRUE\" = \"cyan4\", \"FALSE\" = \"gray80\"), \n                labels = c(\"TRUE\" = \"p < 0.05\", \"FALSE\" = \"p ≥ 0.05\")) +\n  labs(x = \"Environmental variable\", \n       y = \"R² Proportion of Variance Explained\", \n       fill = \"Significance\") +\n  theme_classic() +\n  theme(\n    axis.text = element_text(size = 9),\n    axis.title = element_text(size = 12),\n    legend.text = element_text(size = 12),\n    legend.title = element_text(size = 12),\n    plot.title = element_text(size = 12))\n\n# show\npermanova_plot\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"Figures/interior_mangroves/Physicochemyc_Significance.pdf\", permanova_plot, bg='transparent', width = 5.7, height = 4)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :\nfor 'p ≥ 0.05' in 'mbcsToSbcs': >= substituted for ≥ (U+2265)\n```\n\n\n:::\n:::\n\n\n## 03.7 dbRDA Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract site scores\nscores_samples <- scores(dbrda_result, display = \"sites\")\n\n# Convert to data.frame\nscores_df <- data.frame(scores_samples, Location = phychem$Locality)\n\n# Extra environmental scores\nenv_scores <- scores(dbrda_result, display = \"bp\")\nenv_scores_df <- data.frame(env_scores)\nenv_scores_df$Variable <- rownames(env_scores_df)\n\n# Explain variance percentage\nexplained_var <- summary(dbrda_result)$cont$importance[2, 1:2] * 100  # CAP1 and CAP2\n\n#plot\ncapphychem_plot <- ggplot(scores_df, aes(x = CAP1, y = CAP2, \n  color = Location)) + geom_point(size = 5) + theme_classic() +  \n  labs(\n    col = \"Location\",\n    title = \"db-RDA Unweighted UniFrac\",\n    x = paste0(\"CAP1 (\", round(explained_var[1], 1), \"%)\"),\n    y = paste0(\"CAP2 (\", round(explained_var[2], 1), \"%)\")\n  ) +\n  scale_color_manual(values = loc_colors) +  \n  geom_segment(data = env_scores_df, aes(\n    x = 0, y = 0, xend = CAP1, yend = CAP2),\n               arrow = arrow(length = unit(0.15, \"cm\")), \n    color = \"gray20\", size = 0.6) +\n  # environmental variables\n  geom_text(data = env_scores_df, aes(x = CAP1 * 1.1, \n                            y = CAP2 * 1.1, label = Variable),\n            color = \"black\", size = 3.5) +\n  theme(legend.position = \"right\")\n\ncapphychem_plot\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#save\nggsave(\"Figures/interior_mangroves/dbRDA.pdf\", capphychem_plot, width = 6, height = 4)\n```\n:::\n\n\n# Save rds plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save plots\nnmds_u\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n\n```{.r .cell-code}\nnmds_wu_fltr\n```\n\n::: {.cell-output-display}\n![](03.3.BetaDiversity_files/figure-html/unnamed-chunk-43-2.png){width=672}\n:::\n\n```{.r .cell-code}\nsaveRDS(nmds_u, \"rds/interior_mangroves/nmds_u.rds\")\nsaveRDS(nmds_wu_fltr, \"rds/interior_mangroves/nmds_wu.rds\")\nsaveRDS(capphychem_plot, \"rds/interior_mangroves/dbRDA.rds\")\n```\n:::\n\n\n# Supplementary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n#extract permanova\ntableS10_permanova_u <- as.data.frame(adonis2_unifrac) %>%\n  mutate(Factor = rownames(.)) %>%\n  dplyr::select(Factor, Df, SumOfSqs, R2, F.Model = F, p_value = `Pr(>F)`) %>%\n  filter(!Factor %in% c(\"Total\", \"Residual\")) %>%\n  mutate(across(where(is.numeric), ~ round(., 4)))\n\ntableS10_permanova_wu <- as.data.frame(adonis2_wunifrac_fltr) %>%\n  mutate(Factor = rownames(.)) %>%\n  dplyr::select(Factor, Df, SumOfSqs, R2, F.Model = F, p_value = `Pr(>F)`) %>%\n  filter(!Factor %in% c(\"Total\", \"Residual\")) %>%\n  mutate(across(where(is.numeric), ~ round(., 4)))\n\n# Extract PERMDISP\np_dispersion_u <- anova(beta_disp_u)$`Pr(>F)`[1]\np_dispersion_wu <- anova(beta_disp_fltr)$`Pr(>F)`[1]\n\n# join\ntableS10_final <- tableS10_permanova_u %>%\n  mutate(Dispersion_p = ifelse(Factor == \"Location\", p_dispersion_u, NA)) %>%\n  mutate(Dispersion_p = ifelse(Factor == \"Depths\", p_dispersion_wu, NA)) %>%\n  mutate(across(where(is.numeric), ~ round(., 4)))\n\n#show\ntableS10_final\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Factor Df SumOfSqs     R2 F.Model p_value Dispersion_p\nLocation Location  2   1.4859 0.3011 11.7586   0.001           NA\nDepths     Depths  3   0.6691 0.1356  3.5300   0.001       0.5587\n```\n\n\n:::\n\n```{.r .cell-code}\n#save\nwrite.csv(tableS10_final, \"Tables/interior_mangroves/Supplementary_Table_S10_Interior_BetaDisper.csv\", row.names = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# extract unweighted UniFrac \ntab_u <- as.data.frame(adonis2_unifrac) %>%\n  mutate(Factor = rownames(.), Metric = \"Unweighted UniFrac\") %>%\n  dplyr::select(Metric, Factor, Df, R2, F.Model = F, p_value = `Pr(>F)`) %>%\n  filter(!Factor %in% c(\"Total\", \"Residual\")) %>%\n  mutate(Dispersion_p = case_when(\n    Factor == \"Location\" ~ anova(beta_disp_u)$`Pr(>F)`[1],\n    Factor == \"Depths\" ~ anova(beta_disp_u_d)$`Pr(>F)`[1],\n    TRUE ~ NA_real_\n  ))\n\n# extract weighted UniFrac \ntab_wu <- as.data.frame(adonis2_wunifrac_fltr) %>%\n  mutate(Factor = rownames(.), Metric = \"Weighted UniFrac\") %>%\n  dplyr::select(Metric, Factor, Df, R2, F.Model = F, p_value = `Pr(>F)`) %>%\n  filter(!Factor %in% c(\"Total\", \"Residual\")) %>%\n  mutate(Dispersion_p = case_when(\n    Factor == \"Depths_fltr\" ~ anova(beta_disp_fltr)$`Pr(>F)`[1],\n    Factor == \"Location\" ~ anova(beta_disp_fltr_loc)$`Pr(>F)`[1],\n    TRUE ~ NA_real_\n  ))\n\n# join\ntableS10_final <- bind_rows(tab_u, tab_wu) %>%\n  mutate(across(where(is.numeric), ~ round(., 4)))\n\n# Guardar\nwrite.csv(tableS10_final, \"Tables/interior_mangroves/Supplementary_Table_S10_Interior_Mangroves_Beta.csv\", row.names = FALSE)\n```\n:::\n\n\n# 04. Core-level analysis — Reviewer 2, point 4\n\n::: callout-note\n`Location` es constante dentro de un core, por lo que no puede probarse con `strata = ID`. Se colapsa cada core a UN perfil usando los tres horizontes presentes en los 13 cores (0–15, 16–30, 31–45 cm) para que todos los perfiles representen el mismo rango de profundidad, y se usa el core como unidad independiente. Se corren weighted y unweighted UniFrac. La profundidad conserva su test con `strata = ID` (secciones 01–02).\n:::\n\n## 04.1 Colapso a un perfil por core (3 horizontes comunes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhorizons <- c(\"0-15\",\"16-30\",\"31-45\")   # se excluye 50-75: S6A/S6B (Fossil) no lo tienen,\n                                         # así cada perfil cubre el mismo rango de profundidad\notu_sxt <- as(t(otu_table(ps, taxa_are_rows = TRUE)), \"matrix\")\nmd <- data.frame(sample_data(ps)); md$CoreID <- as.character(md$ID)\n\nmd_k  <- md[md$Depths %in% horizons, ]; otu_k <- otu_sxt[rownames(md_k), ]\ncat(\"Horizontes usados por core:\\n\"); print(table(md_k$CoreID, md_k$Depths))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHorizontes usados por core:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      0-15 16-30 31-45 50-75\n  S1A    1     1     1     0\n  S1B    1     1     1     0\n  S2A    1     1     1     0\n  S2B    1     1     1     0\n  S3A    1     1     1     0\n  S3B    1     1     1     0\n  S4B    1     1     1     0\n  S5A    1     1     1     0\n  S5B    1     1     1     0\n  S6A    1     1     1     0\n  S6B    1     1     1     0\n  S7A    1     1     1     0\n  S7B    1     1     1     0\n```\n\n\n:::\n\n```{.r .cell-code}\nagg_mean <- function(mat, grp){ s <- rowsum(mat, grp); s / as.vector(table(grp)[rownames(s)]) }\ncore_prof <- agg_mean(otu_k, md_k$CoreID)   # 1 perfil por core = media de sus 3 horizontes\n\ncore_md <- md_k[!duplicated(md_k$CoreID), ]; rownames(core_md) <- core_md$CoreID\ncore_md <- core_md[rownames(core_prof), ]\ncat(\"\\nn de cores por Location:\\n\"); print(table(core_md$Location))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nn de cores por Location:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Fossil Lagoon Reforma Waterfalls     Miguelito Dike \n                 4                  3                  6 \n```\n\n\n:::\n:::\n\n\n#### 04.2 Reconstruir phyloseq con los perfiles + el mismo árbol\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncore_ps <- phyloseq(otu_table(t(core_prof), taxa_are_rows = TRUE),\n                    phy_tree(ps), sample_data(core_md))\ncore_ps <- prune_taxa(taxa_sums(core_ps) > 0, core_ps)\ncmd <- data.frame(sample_data(core_ps))     # metadata alineada al orden del objeto\n```\n:::\n\n\n## 04.3 Weighted UniFrac — PERMANOVA + PERMDISP (Location, sin strata)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nwu_core <- UniFrac(core_ps, weighted = TRUE)\nprint(adonis2(wu_core ~ Location, data = cmd, permutations = 999, by = \"terms\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = wu_core ~ Location, data = cmd, permutations = 999, by = \"terms\")\n         Df SumOfSqs      R2      F Pr(>F)  \nLocation  2 0.079337 0.42318 3.6682  0.016 *\nResidual 10 0.108140 0.57682                \nTotal    12 0.187476 1.00000                \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ndisp_wu <- betadisper(wu_core, cmd$Location)\ndisp_wu$group.distances\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Fossil Lagoon Reforma Waterfalls     Miguelito Dike \n        0.05199018         0.07945130         0.09538883 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(123)\npermutest(disp_wu, permutations = 9999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 9999\n\nResponse: Distances\n          Df    Sum Sq   Mean Sq      F N.Perm Pr(>F)\nGroups     2 0.0045249 0.0022625 0.7354   9999 0.5462\nResiduals 10 0.0307649 0.0030765                     \n```\n\n\n:::\n:::\n\n\n## 04.4 Unweighted UniFrac — PERMANOVA + PERMDISP (Location, sin strata) · Fig. 5D\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nu_core <- UniFrac(core_ps, weighted = FALSE)\nprint(adonis2(u_core ~ Location, data = cmd, permutations = 999, by = \"terms\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for adonis under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nadonis2(formula = u_core ~ Location, data = cmd, permutations = 999, by = \"terms\")\n         Df SumOfSqs      R2     F Pr(>F)    \nLocation  2  0.30352 0.52999 5.638  0.001 ***\nResidual 10  0.26917 0.47001                 \nTotal    12  0.57269 1.00000                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ndisp_u <- betadisper(u_core, cmd$Location)\ndisp_u$group.distances\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Fossil Lagoon Reforma Waterfalls     Miguelito Dike \n        0.09118611         0.09830273         0.16588313 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(123)\npermutest(disp_u, permutations = 9999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPermutation test for homogeneity of multivariate dispersions\nPermutation: free\nNumber of permutations: 9999\n\nResponse: Distances\n          Df   Sum Sq   Mean Sq      F N.Perm Pr(>F)\nGroups     2 0.016671 0.0083357 1.5071   9999 0.2557\nResiduals 10 0.055311 0.0055311                     \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "03.3.BetaDiversity_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}